language: python  
sudo: required  
dist: trusty
python: 3.6
script:    
  - python ./PyDisco/Disco/Tests.py
notifications:
  email:
    on_success: never # default: change
    on_failure: change # default: always
